---

name: CI

on:
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]

env:
  CARGO_TERM_COLOR: true

jobs:
  build:
    runs-on: ubunut-latest
    steps:
      - uses: actions/checkout@v3
      - name: Cache
        uses: actions/cache@v3.2.2
        with:
          path: target
          key: build-output
          upload-chunk-size: 10000
      - name: Release-Build
        run: rm -rf target/ ; cargo build -vv --release --all-features
      - name: Simple Manual Testsuite
        run: ./manual-tests

